name: MikaDirectional
version: '${project.version}'
main: io.github.mikalooloo.mikadirectional.MikaDirectional
api-version: 1.18
authors: [ Mikalooloo ]
description: This plugin adds user-toggleable coordinates and direction in the action bar.
website: https://mikalooloo.github.io/
commands:
  mikadirectional:
    description: Displays commands
    usage: /md
    aliases: [md]